specVersion: 0.2.0
name: shiden-stats-indexer
version: 0.0.1
description: Shiden statistics indexer
repository: 'https://github.com/subquery/shiden-subql-starters'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://shiden.api.onfinality.io/public-wss'
  genesisHash: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
  dictionary: 'https://api.subquery.network/sq/subquery/shiden-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
